# source('http://bioconductor.org/biocLite.R')
# biocLite('rhdf5')
# biocLite('tximport')
# biocLite('biomaRt')
# biocLite('remotes')
# biocLite('pachterlab/sleuth')
# biocLite('EnsDb.Hsapiens.v86')
# biocLite('EnsDb.Mmusculus.v79')

install.packages('BiocManager')
BiocManager::install('rhdf5')
BiocManager::install('tximport')
BiocManager::install('biomaRt')
BiocManager::install('remotes')
BiocManager::install('pachterlab/sleuth')
BiocManager::install('EnsDb.Hsapiens.v86')
BiocManager::install('EnsDb.Mmusculus.v79')
BiocManager::install('limma')
BiocManager::install('edgeR')
install.packages('readr')
install.packages('data.table')
install.packages('jsonlite')
